"use strict";

const { VersionConflictError } = require("./interface");

const GITHUB_API = "https://api.github.com";
const VAULT_FILENAME = ".cdx-vault.json";
const README_FILENAME = "README.md";
const README_BODY = "cdx-sync vault — do not edit by hand. Generated by https://github.com/codex-account-switcher\n";
const USER_AGENT = "cdx-sync";

function createGistBackend(options = {}) {
  let token = typeof options.token === "string" ? options.token : "";
  let gistId = typeof options.gistId === "string" ? options.gistId : "";
  const fetchImpl = typeof options.fetch === "function" ? options.fetch : globalThis.fetch;
  if (typeof fetchImpl !== "function") {
    throw new Error("global fetch unavailable; pass `fetch` in options or upgrade Node to >=18");
  }
  const apiBase = typeof options.apiBase === "string" && options.apiBase ? options.apiBase : GITHUB_API;

  function headers(extra = {}) {
    if (!token) {
      throw new Error("gist backend has no token configured");
    }
    return {
      Authorization: `token ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": USER_AGENT,
      ...extra,
    };
  }

  async function request(method, path, body) {
    const init = { method, headers: headers(body ? { "Content-Type": "application/json" } : {}) };
    if (body !== undefined) {
      init.body = JSON.stringify(body);
    }
    const response = await fetchImpl(`${apiBase}${path}`, init);
    if (!response.ok) {
      const text = await safeReadText(response);
      const err = new Error(friendlyError(method, path, response.status, response.statusText, text));
      err.status = response.status;
      throw err;
    }
    if (response.status === 204) {
      return null;
    }
    return response.json();
  }

  function friendlyError(method, requestPath, status, statusText, text) {
    if (status === 401) {
      return "GitHub rejected the token (401). The PAT may be expired or revoked — generate a new one at https://github.com/settings/tokens (scope: gist) and reconnect cloud sync.";
    }
    if (status === 404 && /\/gists\/[^/]+$/.test(requestPath)) {
      return "The vault gist no longer exists on GitHub (404). It was probably deleted from the web. Disconnect cloud sync and reconnect to create a new gist.";
    }
    if (status === 403) {
      return "GitHub denied the request (403). Check that the token has the 'gist' scope.";
    }
    const trimmed = text ? ` — ${text}` : "";
    return `gist API ${method} ${requestPath} failed: ${status} ${statusText}${trimmed}`;
  }

  async function safeReadText(response) {
    try {
      const text = await response.text();
      return text ? text.slice(0, 300) : "";
    } catch (_) {
      return "";
    }
  }

  async function findExistingGist() {
    let page = 1;
    const perPage = 100;
    while (page <= 10) {
      const list = await request("GET", `/gists?per_page=${perPage}&page=${page}`);
      if (!Array.isArray(list) || list.length === 0) {
        return null;
      }
      for (const entry of list) {
        if (entry && entry.files && Object.prototype.hasOwnProperty.call(entry.files, VAULT_FILENAME)) {
          return entry.id;
        }
      }
      if (list.length < perPage) {
        return null;
      }
      page += 1;
    }
    return null;
  }

  async function createVaultGist() {
    const payload = {
      description: "cdx-sync vault",
      public: false,
      files: {
        [README_FILENAME]: { content: README_BODY },
      },
    };
    const created = await request("POST", "/gists", payload);
    if (!created || typeof created.id !== "string") {
      throw new Error("gist creation returned no id");
    }
    return created.id;
  }

  return {
    async isConfigured() {
      return !!(token && gistId);
    },

    async init(creds = {}) {
      if (typeof creds.token === "string" && creds.token) {
        token = creds.token;
      }
      if (typeof creds.gistId === "string" && creds.gistId) {
        gistId = creds.gistId;
      }
      if (!token) {
        throw new Error("gist backend requires a `token` in creds");
      }

      const user = await request("GET", "/user");
      if (!user || typeof user.login !== "string") {
        throw new Error("gist backend could not identify token owner");
      }

      if (!gistId) {
        gistId = (await findExistingGist()) || (await createVaultGist());
      } else {
        await request("GET", `/gists/${gistId}`);
      }

      return { token, gistId, login: user.login };
    },

    async pull() {
      if (!gistId) {
        throw new Error("gist backend not initialized");
      }
      const gist = await request("GET", `/gists/${gistId}`);
      const files = gist && gist.files ? gist.files : {};
      const file = files[VAULT_FILENAME];
      if (!file || typeof file.content !== "string" || file.content.length === 0) {
        return null;
      }
      const version = typeof gist.updated_at === "string" ? gist.updated_at : "";
      if (!version) {
        throw new Error("gist response missing updated_at");
      }
      return { blob: file.content, version };
    },

    async push(blob, expectedVersion) {
      if (!gistId) {
        throw new Error("gist backend not initialized");
      }
      if (typeof blob !== "string" || !blob) {
        throw new Error("blob must be a non-empty string");
      }

      if (expectedVersion !== null) {
        const current = await request("GET", `/gists/${gistId}`);
        const currentVersion = current && typeof current.updated_at === "string" ? current.updated_at : "";
        if (currentVersion !== expectedVersion) {
          throw new VersionConflictError();
        }
      }

      const payload = {
        files: {
          [VAULT_FILENAME]: { content: blob },
        },
      };
      const updated = await request("PATCH", `/gists/${gistId}`, payload);
      if (!updated || typeof updated.updated_at !== "string") {
        throw new Error("gist PATCH response missing updated_at");
      }
      return updated.updated_at;
    },
  };
}

module.exports = {
  createGistBackend,
  VAULT_FILENAME,
};
